# Generated by Django 3.1.1 on 2020-09-24 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BASE_APP', '0002_auto_20200923_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Post',
            new_name='Postuser',
        ),
    ]
