# Generated by Django 3.1.1 on 2020-10-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE_APP', '0004_auto_20201001_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_create_news', 'Can create news'),)},
        ),
    ]
