# Generated by Django 3.1.1 on 2020-11-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BASE_APP', '0005_auto_20201006_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_create_news', 'Can create news'), ('can_update_news', 'Can update news'))},
        ),
    ]
