# Generated by Django 3.1.1 on 2020-11-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0002_auto_20201105_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
