# Generated by Django 3.1.1 on 2020-11-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0004_auto_20201105_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to=''),
        ),
    ]
