# Generated by Django 3.1.1 on 2020-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0005_auto_20201105_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='ProfilePictures'),
        ),
    ]
