# Generated by Django 3.1.7 on 2021-05-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BASE_APP', '0006_auto_20201104_0013'),
        ('USER_APP', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BASE_APP.news'),
        ),
    ]
