# Generated by Django 3.1.7 on 2021-05-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0009_productopinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='ProfilePictures'),
        ),
    ]
