# Generated by Django 3.1.7 on 2021-05-17 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USER_APP', '0012_auto_20210517_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopinion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default_profile.jpg', null=True, upload_to='ProfilePictures'),
        ),
    ]
