# Generated by Django 3.1.1 on 2020-11-05 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP_APP', '0007_auto_20201021_0229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
