# Generated by Django 3.1.1 on 2020-11-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP_APP', '0009_auto_20201112_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SHOP_APP.product'),
        ),
    ]
