# Generated by Django 3.1.1 on 2020-11-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP_APP', '0011_auto_20201125_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
