# Generated by Django 3.1.7 on 2021-06-28 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP_APP', '0023_auto_20210629_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SHOP_APP.category'),
        ),
    ]
