# Generated by Django 3.1.7 on 2021-07-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SHOP_APP', '0027_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
